-- =============================================================================
-- Vomatt API - Complete Database Schema
-- Database: PostgreSQL
-- Schema: vomatt
-- ID Strategy: UUID v7 (time-ordered, generated by application via Hibernate UuidGenerator)
-- =============================================================================

-- =============================================================================
-- 1. ROLES (角色表)
-- =============================================================================
CREATE TABLE IF NOT EXISTS vomatt.roles (
    id         UUID         PRIMARY KEY,
    name       VARCHAR(20)  NOT NULL UNIQUE,
    created_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- =============================================================================
-- 2. USERS (使用者表)
-- =============================================================================
-- Note: credential stores BCrypt hashed password / OTP code
CREATE TABLE IF NOT EXISTS vomatt.users (
    id                       UUID         PRIMARY KEY,
    username                 VARCHAR(50)  NOT NULL UNIQUE,
    email                    VARCHAR(50)  NOT NULL UNIQUE,
    phone_number             VARCHAR(20)  UNIQUE,
    credential               VARCHAR(120),
    verification_code_expiry TIMESTAMP,
    created_at               TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at               TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_login_at            TIMESTAMP,
    login_attempts           INTEGER      NOT NULL DEFAULT 0,
    locked_until             TIMESTAMP,
    points                   INTEGER      NOT NULL DEFAULT 0,
    membership_level         VARCHAR(20)  NOT NULL DEFAULT 'BASIC',
    active                   BOOLEAN      NOT NULL DEFAULT TRUE,
    first_name               VARCHAR(50),
    last_name                VARCHAR(50),
    location                 VARCHAR(100),
    display_name             VARCHAR(100),
    bio                      TEXT
);

-- =============================================================================
-- 3. USER_ROLES (使用者角色關聯表)
-- =============================================================================
CREATE TABLE IF NOT EXISTS vomatt.user_roles (
    user_id UUID NOT NULL,
    role_id UUID NOT NULL,
    PRIMARY KEY (user_id, role_id),
    CONSTRAINT fk_user_roles_user FOREIGN KEY (user_id) REFERENCES vomatt.users (id) ON DELETE CASCADE,
    CONSTRAINT fk_user_roles_role FOREIGN KEY (role_id) REFERENCES vomatt.roles (id) ON DELETE CASCADE
);

-- =============================================================================
-- 4. USER_PREFERENCES (使用者偏好設定表)
-- =============================================================================
CREATE TABLE IF NOT EXISTS vomatt.user_preferences (
    id               UUID         PRIMARY KEY,
    user_id          UUID         NOT NULL,
    preference_key   VARCHAR(50)  NOT NULL,
    preference_value TEXT,
    created_at       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (user_id, preference_key),
    CONSTRAINT fk_user_preferences_user FOREIGN KEY (user_id) REFERENCES vomatt.users (id) ON DELETE CASCADE
);

-- =============================================================================
-- 5. USER_ACTIVITIES (使用者活動記錄表)
-- =============================================================================
CREATE TABLE IF NOT EXISTS vomatt.user_activities (
    id                   UUID         PRIMARY KEY,
    user_id              UUID         NOT NULL,
    activity_type        VARCHAR(30)  NOT NULL,
    activity_description TEXT,
    ip_address           VARCHAR(45),
    user_agent           TEXT,
    created_at           TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at           TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_user_activities_user FOREIGN KEY (user_id) REFERENCES vomatt.users (id) ON DELETE CASCADE
);

-- =============================================================================
-- 6. REFRESH_TOKENS (JWT 刷新令牌表)
-- =============================================================================
CREATE TABLE IF NOT EXISTS vomatt.refresh_tokens (
    id          UUID         PRIMARY KEY,
    user_id     UUID         NOT NULL UNIQUE,
    token       VARCHAR(255) NOT NULL UNIQUE,
    expiry_date TIMESTAMP    NOT NULL,
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_refresh_tokens_user FOREIGN KEY (user_id) REFERENCES vomatt.users (id) ON DELETE CASCADE
);

-- =============================================================================
-- 7. PASSWORD_RESET_TOKENS (密碼重置令牌表)
-- =============================================================================
CREATE TABLE IF NOT EXISTS vomatt.password_reset_tokens (
    id          UUID        PRIMARY KEY,
    user_id     UUID        NOT NULL,
    token       VARCHAR(64) NOT NULL UNIQUE,
    expiry_date TIMESTAMP   NOT NULL,
    used        BOOLEAN     NOT NULL DEFAULT FALSE,
    CONSTRAINT fk_password_reset_tokens_user FOREIGN KEY (user_id) REFERENCES vomatt.users (id) ON DELETE CASCADE
);

-- =============================================================================
-- 8. VOTES (投票表)
-- =============================================================================
CREATE TABLE IF NOT EXISTS vomatt.votes (
    id                     UUID          PRIMARY KEY,
    title                  VARCHAR(200)  NOT NULL,
    description            VARCHAR(1000),
    creator_id             UUID          NOT NULL,
    vote_type              VARCHAR(20)   NOT NULL DEFAULT 'STANDARD',
    start_time             TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    end_time               TIMESTAMP,
    is_active              BOOLEAN       NOT NULL DEFAULT TRUE,
    allow_multiple_choices BOOLEAN       NOT NULL DEFAULT FALSE,
    is_anonymous           BOOLEAN       NOT NULL DEFAULT FALSE,
    is_public              BOOLEAN       NOT NULL DEFAULT TRUE,
    max_choices            INTEGER       NOT NULL DEFAULT 1,
    created_at             TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at             TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_votes_creator FOREIGN KEY (creator_id) REFERENCES vomatt.users (id) ON DELETE CASCADE
);

-- =============================================================================
-- 9. VOTE_OPTIONS (投票選項表)
-- =============================================================================
CREATE TABLE IF NOT EXISTS vomatt.vote_options (
    id            UUID         PRIMARY KEY,
    text          VARCHAR(200) NOT NULL,
    description   VARCHAR(500),
    vote_id       UUID         NOT NULL,
    display_order INTEGER      NOT NULL DEFAULT 0,
    image_url     VARCHAR(500),
    created_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_vote_options_vote FOREIGN KEY (vote_id) REFERENCES vomatt.votes (id) ON DELETE CASCADE
);

-- =============================================================================
-- 10. USER_VOTES (使用者投票記錄表)
-- =============================================================================
CREATE TABLE IF NOT EXISTS vomatt.user_votes (
    id         UUID        PRIMARY KEY,
    user_id    UUID        NOT NULL,
    vote_id    UUID        NOT NULL,
    option_id  UUID        NOT NULL,
    ip_address VARCHAR(45),
    created_at TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (user_id, vote_id, option_id),
    CONSTRAINT fk_user_votes_user   FOREIGN KEY (user_id)   REFERENCES vomatt.users (id)        ON DELETE CASCADE,
    CONSTRAINT fk_user_votes_vote   FOREIGN KEY (vote_id)   REFERENCES vomatt.votes (id)        ON DELETE CASCADE,
    CONSTRAINT fk_user_votes_option FOREIGN KEY (option_id) REFERENCES vomatt.vote_options (id) ON DELETE CASCADE
);

-- =============================================================================
-- 11. USER_RANKINGS (排名投票記錄表，RANKING 類型專用)
-- =============================================================================
CREATE TABLE IF NOT EXISTS vomatt.user_rankings (
    id            UUID        PRIMARY KEY,
    user_id       UUID        NOT NULL,
    vote_id       UUID        NOT NULL,
    option_id     UUID        NOT NULL,
    rank_position INTEGER     NOT NULL,
    created_at    TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (user_id, vote_id, option_id),
    CONSTRAINT fk_user_rankings_user   FOREIGN KEY (user_id)   REFERENCES vomatt.users (id)        ON DELETE CASCADE,
    CONSTRAINT fk_user_rankings_vote   FOREIGN KEY (vote_id)   REFERENCES vomatt.votes (id)        ON DELETE CASCADE,
    CONSTRAINT fk_user_rankings_option FOREIGN KEY (option_id) REFERENCES vomatt.vote_options (id) ON DELETE CASCADE
);

-- =============================================================================
-- 12. USER_RATINGS (評分投票記錄表，RATING 類型專用)
-- =============================================================================
CREATE TABLE IF NOT EXISTS vomatt.user_ratings (
    id         UUID      PRIMARY KEY,
    user_id    UUID      NOT NULL,
    vote_id    UUID      NOT NULL,
    score      INTEGER   NOT NULL CHECK (score >= 1 AND score <= 5),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (user_id, vote_id),
    CONSTRAINT fk_user_ratings_user FOREIGN KEY (user_id) REFERENCES vomatt.users (id) ON DELETE CASCADE,
    CONSTRAINT fk_user_ratings_vote FOREIGN KEY (vote_id) REFERENCES vomatt.votes (id) ON DELETE CASCADE
);

-- =============================================================================
-- 13. VOTE_COMMENTS (投票留言表)
-- =============================================================================
CREATE TABLE IF NOT EXISTS vomatt.vote_comments (
    id         UUID        PRIMARY KEY,
    vote_id    UUID        NOT NULL,
    user_id    UUID        NOT NULL,
    content    TEXT        NOT NULL,
    is_deleted BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_vote_comments_vote FOREIGN KEY (vote_id) REFERENCES vomatt.votes (id) ON DELETE CASCADE,
    CONSTRAINT fk_vote_comments_user FOREIGN KEY (user_id) REFERENCES vomatt.users (id) ON DELETE CASCADE
);

-- =============================================================================
-- 14. COMMENT_LIKES (留言按讚表)
-- =============================================================================
CREATE TABLE IF NOT EXISTS vomatt.comment_likes (
    id         UUID        PRIMARY KEY,
    comment_id UUID        NOT NULL,
    user_id    UUID        NOT NULL,
    created_at TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (comment_id, user_id),
    CONSTRAINT fk_comment_likes_comment FOREIGN KEY (comment_id) REFERENCES vomatt.vote_comments (id) ON DELETE CASCADE,
    CONSTRAINT fk_comment_likes_user    FOREIGN KEY (user_id)    REFERENCES vomatt.users (id)          ON DELETE CASCADE
);

-- =============================================================================
-- 15. TAGS (標籤表)
-- =============================================================================
CREATE TABLE IF NOT EXISTS vomatt.tags (
    id            UUID         PRIMARY KEY,
    name          VARCHAR(30)  NOT NULL,
    slug          VARCHAR(50)  NOT NULL,
    description   VARCHAR(200),
    display_order INTEGER      NOT NULL DEFAULT 0,
    usage_count   INTEGER      NOT NULL DEFAULT 0,
    created_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_tags_name UNIQUE (name),
    CONSTRAINT uk_tags_slug UNIQUE (slug)
);

-- =============================================================================
-- 16. VOTE_TAGS (投票標籤關聯表)
-- =============================================================================
CREATE TABLE IF NOT EXISTS vomatt.vote_tags (
    vote_id UUID NOT NULL,
    tag_id  UUID NOT NULL,
    PRIMARY KEY (vote_id, tag_id),
    CONSTRAINT fk_vote_tags_vote FOREIGN KEY (vote_id) REFERENCES vomatt.votes (id) ON DELETE CASCADE,
    CONSTRAINT fk_vote_tags_tag  FOREIGN KEY (tag_id)  REFERENCES vomatt.tags (id)  ON DELETE RESTRICT
);

-- =============================================================================
-- 17. AUDIT_LOGS (系統稽核日誌表)
-- =============================================================================
CREATE TABLE IF NOT EXISTS vomatt.audit_logs (
    id            UUID         PRIMARY KEY,
    user_id       UUID,
    username      VARCHAR(50),
    action        VARCHAR(50)  NOT NULL,
    resource_type VARCHAR(50)  NOT NULL,
    resource_id   VARCHAR(36),
    ip_address    VARCHAR(45),
    user_agent    TEXT,
    request_uri   VARCHAR(500),
    http_method   VARCHAR(10),
    success       BOOLEAN      NOT NULL DEFAULT TRUE,
    error_message TEXT,
    details       TEXT,
    created_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_audit_logs_user FOREIGN KEY (user_id) REFERENCES vomatt.users (id) ON DELETE SET NULL
);

-- =============================================================================
-- INDEXES
-- =============================================================================

-- users
CREATE INDEX IF NOT EXISTS idx_users_username     ON vomatt.users (username);
CREATE INDEX IF NOT EXISTS idx_users_email        ON vomatt.users (email);
CREATE INDEX IF NOT EXISTS idx_users_membership   ON vomatt.users (membership_level);
CREATE INDEX IF NOT EXISTS idx_users_active       ON vomatt.users (active);
CREATE INDEX IF NOT EXISTS idx_users_first_name   ON vomatt.users (first_name);
CREATE INDEX IF NOT EXISTS idx_users_last_name    ON vomatt.users (last_name);
CREATE INDEX IF NOT EXISTS idx_users_location     ON vomatt.users (location);

-- user_activities
CREATE INDEX IF NOT EXISTS idx_user_activities_user_id    ON vomatt.user_activities (user_id);
CREATE INDEX IF NOT EXISTS idx_user_activities_type       ON vomatt.user_activities (activity_type);
CREATE INDEX IF NOT EXISTS idx_user_activities_created_at ON vomatt.user_activities (created_at);

-- votes
CREATE INDEX IF NOT EXISTS idx_votes_creator_id  ON vomatt.votes (creator_id);
CREATE INDEX IF NOT EXISTS idx_votes_vote_type   ON vomatt.votes (vote_type);
CREATE INDEX IF NOT EXISTS idx_votes_is_active   ON vomatt.votes (is_active);
CREATE INDEX IF NOT EXISTS idx_votes_is_public   ON vomatt.votes (is_public);
CREATE INDEX IF NOT EXISTS idx_votes_start_time  ON vomatt.votes (start_time);
CREATE INDEX IF NOT EXISTS idx_votes_end_time    ON vomatt.votes (end_time);
CREATE INDEX IF NOT EXISTS idx_votes_created_at  ON vomatt.votes (created_at);

-- vote_options
CREATE INDEX IF NOT EXISTS idx_vote_options_vote_id       ON vomatt.vote_options (vote_id);
CREATE INDEX IF NOT EXISTS idx_vote_options_display_order ON vomatt.vote_options (vote_id, display_order);

-- user_votes
CREATE INDEX IF NOT EXISTS idx_user_votes_user_id    ON vomatt.user_votes (user_id);
CREATE INDEX IF NOT EXISTS idx_user_votes_vote_id    ON vomatt.user_votes (vote_id);
CREATE INDEX IF NOT EXISTS idx_user_votes_option_id  ON vomatt.user_votes (option_id);
CREATE INDEX IF NOT EXISTS idx_user_votes_created_at ON vomatt.user_votes (created_at);

-- user_rankings
CREATE INDEX IF NOT EXISTS idx_user_rankings_user_vote ON vomatt.user_rankings (user_id, vote_id);
CREATE INDEX IF NOT EXISTS idx_user_rankings_vote_id   ON vomatt.user_rankings (vote_id);

-- user_ratings
CREATE INDEX IF NOT EXISTS idx_user_ratings_user_vote ON vomatt.user_ratings (user_id, vote_id);
CREATE INDEX IF NOT EXISTS idx_user_ratings_vote_id   ON vomatt.user_ratings (vote_id);

-- vote_comments
CREATE INDEX IF NOT EXISTS idx_vote_comments_vote_id    ON vomatt.vote_comments (vote_id);
CREATE INDEX IF NOT EXISTS idx_vote_comments_user_id    ON vomatt.vote_comments (user_id);
CREATE INDEX IF NOT EXISTS idx_vote_comments_created_at ON vomatt.vote_comments (created_at);
CREATE INDEX IF NOT EXISTS idx_vote_comments_is_deleted ON vomatt.vote_comments (is_deleted);

-- comment_likes
CREATE INDEX IF NOT EXISTS idx_comment_likes_comment_id ON vomatt.comment_likes (comment_id);
CREATE INDEX IF NOT EXISTS idx_comment_likes_user_id    ON vomatt.comment_likes (user_id);
CREATE INDEX IF NOT EXISTS idx_comment_likes_created_at ON vomatt.comment_likes (created_at);

-- tags
CREATE INDEX IF NOT EXISTS idx_tags_usage_count ON vomatt.tags (usage_count DESC);

-- vote_tags
CREATE INDEX IF NOT EXISTS idx_vote_tags_tag_id ON vomatt.vote_tags (tag_id);

-- audit_logs
CREATE INDEX IF NOT EXISTS idx_audit_logs_user_id    ON vomatt.audit_logs (user_id);
CREATE INDEX IF NOT EXISTS idx_audit_logs_action     ON vomatt.audit_logs (action);
CREATE INDEX IF NOT EXISTS idx_audit_logs_resource   ON vomatt.audit_logs (resource_type, resource_id);
CREATE INDEX IF NOT EXISTS idx_audit_logs_created_at ON vomatt.audit_logs (created_at);
CREATE INDEX IF NOT EXISTS idx_audit_logs_success    ON vomatt.audit_logs (success);
CREATE INDEX IF NOT EXISTS idx_audit_logs_ip_address ON vomatt.audit_logs (ip_address);

-- =============================================================================
-- SEED DATA
-- =============================================================================

INSERT INTO vomatt.roles (id, name)
VALUES
    (gen_random_uuid(), 'ROLE_USER'),
    (gen_random_uuid(), 'ROLE_MODERATOR'),
    (gen_random_uuid(), 'ROLE_ADMIN')
ON CONFLICT (name) DO NOTHING;
