-- =============================================================================
-- Vomatt API - Complete Database Schema
-- Database: PostgreSQL
-- Schema: vomatt
-- ID Strategy: UUID v7 (time-ordered, generated by application via Hibernate UuidGenerator)
-- =============================================================================
-- =============================================================================
-- 1. ROLES (角色表)
-- =============================================================================
CREATE TABLE IF NOT EXISTS vomatt.roles (
    id         UUID         PRIMARY KEY,
    name       VARCHAR(20)  NOT NULL UNIQUE,
    created_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- =============================================================================
-- 2. USERS (使用者表)
-- =============================================================================
-- Note: verification_code is used as the hashed password field (BCrypt)
CREATE TABLE IF NOT EXISTS vomatt.users (
    id                       UUID         PRIMARY KEY,
    username                 VARCHAR(50)  NOT NULL UNIQUE,
    email                    VARCHAR(50)  NOT NULL UNIQUE,
    phone_number             VARCHAR(20)  UNIQUE,
    verification_code        VARCHAR(120),                   -- BCrypt hashed password / OTP code
    verification_code_expiry TIMESTAMP,
    created_at               TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at               TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_login_at            TIMESTAMP,
    login_attempts           INTEGER      NOT NULL DEFAULT 0,
    locked_until             TIMESTAMP,
    points                   INTEGER      NOT NULL DEFAULT 0,
    membership_level         VARCHAR(20)  NOT NULL DEFAULT 'BASIC',
    active                   BOOLEAN      NOT NULL DEFAULT TRUE,
    first_name               VARCHAR(50),
    last_name                VARCHAR(50),
    location                 VARCHAR(100)
);

-- =============================================================================
-- 3. USER_ROLES (使用者角色關聯表)
-- =============================================================================
CREATE TABLE IF NOT EXISTS vomatt.user_roles (
    user_id UUID NOT NULL,
    role_id UUID NOT NULL,
    PRIMARY KEY (user_id, role_id)
);

-- =============================================================================
-- 4. USER_PREFERENCES (使用者偏好設定表)
-- =============================================================================
CREATE TABLE IF NOT EXISTS vomatt.user_preferences (
    id               UUID         PRIMARY KEY,
    user_id          UUID         NOT NULL,
    preference_key   VARCHAR(50)  NOT NULL,
    preference_value TEXT,
    created_at       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (user_id, preference_key)
);

-- =============================================================================
-- 5. USER_ACTIVITIES (使用者活動記錄表)
-- =============================================================================
CREATE TABLE IF NOT EXISTS vomatt.user_activities (
    id                   UUID         PRIMARY KEY,
    user_id              UUID         NOT NULL,
    activity_type        VARCHAR(30)  NOT NULL,
    activity_description TEXT,
    ip_address           VARCHAR(45),
    user_agent           TEXT,
    created_at           TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at           TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- =============================================================================
-- 6. REFRESH_TOKENS (JWT 刷新令牌表)
-- =============================================================================
CREATE TABLE IF NOT EXISTS vomatt.refresh_tokens (
    id          UUID         PRIMARY KEY,
    user_id     UUID         NOT NULL UNIQUE,               -- One token per user
    token       VARCHAR(255) NOT NULL UNIQUE,
    expiry_date TIMESTAMP    NOT NULL,
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- =============================================================================
-- 7. PASSWORD_RESET_TOKENS (密碼重置令牌表)
-- =============================================================================
CREATE TABLE IF NOT EXISTS vomatt.password_reset_tokens (
    id          UUID        PRIMARY KEY,
    user_id     UUID        NOT NULL,
    token       VARCHAR(64) NOT NULL UNIQUE,
    expiry_date TIMESTAMP   NOT NULL,
    used        BOOLEAN     NOT NULL DEFAULT FALSE
);

-- =============================================================================
-- 8. VOTES (投票表)
-- =============================================================================
CREATE TABLE IF NOT EXISTS vomatt.votes (
    id                    UUID          PRIMARY KEY,
    title                 VARCHAR(200)  NOT NULL,
    description           VARCHAR(1000),
    creator_id            UUID          NOT NULL,
    start_time            TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    end_time              TIMESTAMP,
    is_active             BOOLEAN       NOT NULL DEFAULT TRUE,
    allow_multiple_choices BOOLEAN      NOT NULL DEFAULT FALSE,
    is_anonymous          BOOLEAN       NOT NULL DEFAULT FALSE,
    is_public             BOOLEAN       NOT NULL DEFAULT TRUE,
    max_choices           INTEGER       NOT NULL DEFAULT 1,
    created_at            TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at            TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- =============================================================================
-- 9. VOTE_OPTIONS (投票選項表)
-- =============================================================================
CREATE TABLE IF NOT EXISTS vomatt.vote_options (
    id            UUID         PRIMARY KEY,
    text          VARCHAR(200) NOT NULL,
    description   VARCHAR(500),
    vote_id       UUID         NOT NULL,
    display_order INTEGER      NOT NULL DEFAULT 0,
    created_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- =============================================================================
-- 10. USER_VOTES (使用者投票記錄表)
-- =============================================================================
CREATE TABLE IF NOT EXISTS vomatt.user_votes (
    id         UUID        PRIMARY KEY,
    user_id    UUID        NOT NULL,
    vote_id    UUID        NOT NULL,
    option_id  UUID        NOT NULL,
    ip_address VARCHAR(45),
    created_at TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (user_id, vote_id, option_id)
);

-- =============================================================================
-- 11. VOTE_COMMENTS (投票留言表)
-- =============================================================================
CREATE TABLE IF NOT EXISTS vomatt.vote_comments (
    id         UUID        PRIMARY KEY,
    vote_id    UUID        NOT NULL,
    user_id    UUID        NOT NULL,
    content    TEXT        NOT NULL,
    is_deleted BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- =============================================================================
-- 12. COMMENT_LIKES (留言按讚表)
-- =============================================================================
CREATE TABLE IF NOT EXISTS vomatt.comment_likes (
    id         UUID        PRIMARY KEY,
    comment_id UUID        NOT NULL,
    user_id    UUID        NOT NULL,
    created_at TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (comment_id, user_id)
);

-- =============================================================================
-- 13. AUDIT_LOGS (系統稽核日誌表)
-- =============================================================================
CREATE TABLE IF NOT EXISTS vomatt.audit_logs (
    id            UUID         PRIMARY KEY,
    user_id       UUID,
    username      VARCHAR(50),
    action        VARCHAR(50)  NOT NULL,
    resource_type VARCHAR(50)  NOT NULL,
    resource_id   VARCHAR(36),
    ip_address    VARCHAR(45),
    user_agent    TEXT,
    request_uri   VARCHAR(500),
    http_method   VARCHAR(10),
    success       BOOLEAN      NOT NULL DEFAULT TRUE,
    error_message TEXT,
    details       TEXT,
    created_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- =============================================================================
-- INDEXES
-- =============================================================================

-- users
CREATE INDEX IF NOT EXISTS vomatt.idx_users_username        ON users (username);
CREATE INDEX IF NOT EXISTS vomatt.idx_users_email           ON users (email);
CREATE INDEX IF NOT EXISTS vomatt.idx_users_membership      ON users (membership_level);
CREATE INDEX IF NOT EXISTS vomatt.idx_users_active          ON users (active);
CREATE INDEX IF NOT EXISTS vomatt.idx_users_first_name      ON users (first_name);
CREATE INDEX IF NOT EXISTS vomatt.idx_users_last_name       ON users (last_name);
CREATE INDEX IF NOT EXISTS vomatt.idx_users_location        ON users (location);

-- user_activities
CREATE INDEX IF NOT EXISTS vomatt.idx_user_activities_user_id   ON user_activities (user_id);
CREATE INDEX IF NOT EXISTS vomatt.idx_user_activities_type      ON user_activities (activity_type);
CREATE INDEX IF NOT EXISTS vomatt.idx_user_activities_created_at ON user_activities (created_at);

-- votes
CREATE INDEX IF NOT EXISTS vomatt.idx_votes_creator_id  ON votes (creator_id);
CREATE INDEX IF NOT EXISTS vomatt.idx_votes_is_active   ON votes (is_active);
CREATE INDEX IF NOT EXISTS vomatt.idx_votes_is_public   ON votes (is_public);
CREATE INDEX IF NOT EXISTS vomatt.idx_votes_start_time  ON votes (start_time);
CREATE INDEX IF NOT EXISTS vomatt.idx_votes_end_time    ON votes (end_time);
CREATE INDEX IF NOT EXISTS vomatt.idx_votes_created_at  ON votes (created_at);

-- vote_options
CREATE INDEX IF NOT EXISTS vomatt.idx_vote_options_vote_id       ON vote_options (vote_id);
CREATE INDEX IF NOT EXISTS vomatt.idx_vote_options_display_order ON vote_options (vote_id, display_order);

-- user_votes
CREATE INDEX IF NOT EXISTS vomatt.idx_user_votes_user_id   ON user_votes (user_id);
CREATE INDEX IF NOT EXISTS vomatt.idx_user_votes_vote_id   ON user_votes (vote_id);
CREATE INDEX IF NOT EXISTS vomatt.idx_user_votes_option_id ON user_votes (option_id);
CREATE INDEX IF NOT EXISTS vomatt.idx_user_votes_created_at ON user_votes (created_at);

-- vote_comments
CREATE INDEX IF NOT EXISTS vomatt.idx_vote_comments_vote_id    ON vote_comments (vote_id);
CREATE INDEX IF NOT EXISTS vomatt.idx_vote_comments_user_id    ON vote_comments (user_id);
CREATE INDEX IF NOT EXISTS vomatt.idx_vote_comments_created_at ON vote_comments (created_at);
CREATE INDEX IF NOT EXISTS vomatt.idx_vote_comments_is_deleted ON vote_comments (is_deleted);

-- comment_likes
CREATE INDEX IF NOT EXISTS vomatt.idx_comment_likes_comment_id ON comment_likes (comment_id);
CREATE INDEX IF NOT EXISTS vomatt.idx_comment_likes_user_id    ON comment_likes (user_id);
CREATE INDEX IF NOT EXISTS vomatt.idx_comment_likes_created_at ON comment_likes (created_at);

-- audit_logs
CREATE INDEX IF NOT EXISTS vomatt.idx_audit_logs_user_id    ON audit_logs (user_id);
CREATE INDEX IF NOT EXISTS vomatt.idx_audit_logs_action     ON audit_logs (action);
CREATE INDEX IF NOT EXISTS vomatt.idx_audit_logs_resource   ON audit_logs (resource_type, resource_id);
CREATE INDEX IF NOT EXISTS vomatt.idx_audit_logs_created_at ON audit_logs (created_at);
CREATE INDEX IF NOT EXISTS vomatt.idx_audit_logs_success    ON audit_logs (success);
CREATE INDEX IF NOT EXISTS vomatt.idx_audit_logs_ip_address ON audit_logs (ip_address);

-- =============================================================================
-- SEED DATA
-- =============================================================================

INSERT INTO roles (name)
VALUES ('ROLE_USER'), ('ROLE_MODERATOR'), ('ROLE_ADMIN')
ON CONFLICT (name) DO NOTHING;
