package com.vomatt.tags;

import com.vomatt.common.exception.ApiException;
import com.vomatt.common.i18n.MessageKey;
import com.vomatt.entity.Tag;
import com.vomatt.repository.TagRepository;
import com.vomatt.tags.dto.CreateTagRequest;
import com.vomatt.common.response.Cursor;
import com.vomatt.common.response.CursorResponse;
import com.vomatt.tags.dto.TagDto;
import com.vomatt.tags.dto.UpdateTagRequest;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageImpl;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Pageable;
import org.springframework.http.HttpStatus;
import org.springframework.test.util.ReflectionTestUtils;

import java.util.List;
import java.util.Optional;
import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.*;

@ExtendWith(MockitoExtension.class)
@DisplayName("TagService")
class TagServiceTest {

    @Mock
    TagRepository tagRepository;

    @InjectMocks
    TagService tagService;

    // ─── helper ───────────────────────────────────────────────────────────────

    private static Tag withId(Tag tag, UUID id) {
        ReflectionTestUtils.setField(tag, "id", id);
        return tag;
    }

    private static Tag createTagWithId(String name, String slug, String description, int displayOrder) {
        return withId(new Tag(name, slug, description, displayOrder), UUID.randomUUID());
    }

    private static void assertApiException(Throwable ex, HttpStatus status, MessageKey key) {
        assertThat(ex).isInstanceOf(ApiException.class);
        ApiException apiEx = (ApiException) ex;
        assertThat(apiEx.getStatus()).isEqualTo(status);
        assertThat(apiEx.getMessageKey()).isEqualTo(key);
    }

    // ─── createTag ────────────────────────────────────────────────────────────

    @Nested
    @DisplayName("createTag")
    class CreateTagTests {

        @Test
        @DisplayName("應該在未提供 slug 時自動生成 slug（Tech News → tech-news）")
        void shouldCreateTagWithAutoGeneratedSlug() {
            CreateTagRequest request = new CreateTagRequest();
            request.setName("Tech News");
            request.setDescription("Technology news");
            request.setDisplayOrder(1);

            when(tagRepository.existsByName("Tech News")).thenReturn(false);
            when(tagRepository.existsBySlug("tech-news")).thenReturn(false);
            when(tagRepository.save(any(Tag.class))).thenAnswer(inv -> withId(inv.getArgument(0), UUID.randomUUID()));

            TagDto result = tagService.createTag(request);

            assertThat(result).isNotNull();
            assertThat(result.getName()).isEqualTo("Tech News");
            assertThat(result.getSlug()).isEqualTo("tech-news");
            assertThat(result.getDescription()).isEqualTo("Technology news");
            assertThat(result.getDisplayOrder()).isEqualTo(1);
            assertThat(result.getUsageCount()).isEqualTo(0);
            assertThat(result.getId()).isNotNull();
        }

        @Test
        @DisplayName("應該在提供 slug 時直接使用（food 保持 food）")
        void shouldUseProvidedSlug() {
            CreateTagRequest request = new CreateTagRequest();
            request.setName("Food");
            request.setSlug("food");
            request.setDisplayOrder(0);

            when(tagRepository.existsByName("Food")).thenReturn(false);
            when(tagRepository.existsBySlug("food")).thenReturn(false);
            when(tagRepository.save(any(Tag.class))).thenAnswer(inv -> withId(inv.getArgument(0), UUID.randomUUID()));

            TagDto result = tagService.createTag(request);

            assertThat(result.getSlug()).isEqualTo("food");
            verify(tagRepository).existsBySlug("food");
        }

        @Test
        @DisplayName("應該在名稱重複時拋出 409 TAG_NAME_EXISTS")
        void shouldThrowWhenNameDuplicate() {
            CreateTagRequest request = new CreateTagRequest();
            request.setName("Tech");

            when(tagRepository.existsByName("Tech")).thenReturn(true);

            assertThatThrownBy(() -> tagService.createTag(request))
                    .satisfies(ex -> assertApiException(ex, HttpStatus.CONFLICT, MessageKey.TAG_NAME_EXISTS));

            verify(tagRepository, never()).save(any());
        }

        @Test
        @DisplayName("應該在 slug 重複時拋出 409 TAG_SLUG_EXISTS")
        void shouldThrowWhenSlugDuplicate() {
            CreateTagRequest request = new CreateTagRequest();
            request.setName("Tech");
            request.setSlug("tech");

            when(tagRepository.existsByName("Tech")).thenReturn(false);
            when(tagRepository.existsBySlug("tech")).thenReturn(true);

            assertThatThrownBy(() -> tagService.createTag(request))
                    .satisfies(ex -> assertApiException(ex, HttpStatus.CONFLICT, MessageKey.TAG_SLUG_EXISTS));

            verify(tagRepository, never()).save(any());
        }
    }

    // ─── updateTag ────────────────────────────────────────────────────────────

    @Nested
    @DisplayName("updateTag")
    class UpdateTagTests {

        @Test
        @DisplayName("應該成功更新標籤欄位並儲存")
        void shouldUpdateTag() {
            UUID tagId = UUID.randomUUID();
            Tag existing = withId(new Tag("OldName", "old-name", "Old desc", 0), tagId);

            UpdateTagRequest request = new UpdateTagRequest();
            request.setName("NewName");
            request.setSlug("new-name");
            request.setDescription("New desc");
            request.setDisplayOrder(5);

            when(tagRepository.findById(tagId)).thenReturn(Optional.of(existing));
            when(tagRepository.existsByNameAndIdNot("NewName", tagId)).thenReturn(false);
            when(tagRepository.existsBySlugAndIdNot("new-name", tagId)).thenReturn(false);
            when(tagRepository.save(any(Tag.class))).thenReturn(existing);

            TagDto result = tagService.updateTag(tagId.toString(), request);

            assertThat(result.getName()).isEqualTo("NewName");
            assertThat(result.getSlug()).isEqualTo("new-name");
            assertThat(result.getDescription()).isEqualTo("New desc");
            assertThat(result.getDisplayOrder()).isEqualTo(5);
            verify(tagRepository).save(existing);
        }

        @Test
        @DisplayName("應該在找不到標籤時拋出 404 TAG_NOT_FOUND")
        void shouldThrowWhenTagNotFound() {
            UUID tagId = UUID.randomUUID();
            when(tagRepository.findById(tagId)).thenReturn(Optional.empty());

            UpdateTagRequest request = new UpdateTagRequest();
            request.setName("AnyName");
            request.setDisplayOrder(0);

            assertThatThrownBy(() -> tagService.updateTag(tagId.toString(), request))
                    .satisfies(ex -> assertApiException(ex, HttpStatus.NOT_FOUND, MessageKey.TAG_NOT_FOUND));
        }

        @Test
        @DisplayName("應該在更新名稱衝突時拋出 409 TAG_NAME_EXISTS")
        void shouldThrowWhenUpdatedNameConflicts() {
            UUID tagId = UUID.randomUUID();
            Tag existing = withId(new Tag("OldName", "old-name", null, 0), tagId);

            UpdateTagRequest request = new UpdateTagRequest();
            request.setName("ConflictName");
            request.setDisplayOrder(0);

            when(tagRepository.findById(tagId)).thenReturn(Optional.of(existing));
            when(tagRepository.existsByNameAndIdNot("ConflictName", tagId)).thenReturn(true);

            assertThatThrownBy(() -> tagService.updateTag(tagId.toString(), request))
                    .satisfies(ex -> assertApiException(ex, HttpStatus.CONFLICT, MessageKey.TAG_NAME_EXISTS));

            verify(tagRepository, never()).save(any());
        }

        @Test
        @DisplayName("應該在更新 slug 衝突時拋出 409 TAG_SLUG_EXISTS")
        void shouldThrowWhenUpdatedSlugConflicts() {
            UUID tagId = UUID.randomUUID();
            Tag existing = withId(new Tag("OldName", "old-name", null, 0), tagId);

            UpdateTagRequest request = new UpdateTagRequest();
            request.setName("NewName");
            request.setSlug("conflict-slug");
            request.setDisplayOrder(0);

            when(tagRepository.findById(tagId)).thenReturn(Optional.of(existing));
            when(tagRepository.existsByNameAndIdNot("NewName", tagId)).thenReturn(false);
            when(tagRepository.existsBySlugAndIdNot("conflict-slug", tagId)).thenReturn(true);

            assertThatThrownBy(() -> tagService.updateTag(tagId.toString(), request))
                    .satisfies(ex -> assertApiException(ex, HttpStatus.CONFLICT, MessageKey.TAG_SLUG_EXISTS));

            verify(tagRepository, never()).save(any());
        }
    }

    // ─── deleteTag ────────────────────────────────────────────────────────────

    @Nested
    @DisplayName("deleteTag")
    class DeleteTagTests {

        @Test
        @DisplayName("應該在標籤未被投票引用時成功刪除")
        void shouldDeleteUnreferencedTag() {
            UUID tagId = UUID.randomUUID();
            Tag tag = withId(new Tag("Tech", "tech", null, 0), tagId);

            when(tagRepository.findById(tagId)).thenReturn(Optional.of(tag));
            when(tagRepository.isTagReferencedByVotes(tagId)).thenReturn(false);

            tagService.deleteTag(tagId.toString());

            verify(tagRepository).delete(tag);
        }

        @Test
        @DisplayName("應該在標籤被投票引用時拋出 409 TAG_IN_USE")
        void shouldThrowConflictWhenTagIsReferenced() {
            UUID tagId = UUID.randomUUID();
            Tag tag = withId(new Tag("Tech", "tech", null, 0), tagId);

            when(tagRepository.findById(tagId)).thenReturn(Optional.of(tag));
            when(tagRepository.isTagReferencedByVotes(tagId)).thenReturn(true);

            assertThatThrownBy(() -> tagService.deleteTag(tagId.toString()))
                    .satisfies(ex -> assertApiException(ex, HttpStatus.CONFLICT, MessageKey.TAG_IN_USE));

            verify(tagRepository, never()).delete(any());
        }

        @Test
        @DisplayName("應該在找不到標籤時拋出 404 TAG_NOT_FOUND")
        void shouldThrowWhenTagNotFoundOnDelete() {
            UUID tagId = UUID.randomUUID();
            when(tagRepository.findById(tagId)).thenReturn(Optional.empty());

            assertThatThrownBy(() -> tagService.deleteTag(tagId.toString()))
                    .satisfies(ex -> assertApiException(ex, HttpStatus.NOT_FOUND, MessageKey.TAG_NOT_FOUND));
        }
    }

    // ─── getAllTags ───────────────────────────────────────────────────────────

    @Nested
    @DisplayName("getAllTags")
    class GetAllTagsTests {

        @Test
        @DisplayName("應該依 displayOrder 排序回傳所有標籤")
        void shouldReturnAllTagsOrderedByDisplayOrder() {
            Tag tag1 = createTagWithId("Alpha", "alpha", null, 1);
            Tag tag2 = createTagWithId("Beta", "beta", null, 2);
            Tag tag3 = createTagWithId("Gamma", "gamma", null, 3);

            when(tagRepository.findAllByOrderByDisplayOrderAsc()).thenReturn(List.of(tag1, tag2, tag3));

            List<TagDto> result = tagService.getAllTags();

            assertThat(result).hasSize(3);
            assertThat(result.get(0).getName()).isEqualTo("Alpha");
            assertThat(result.get(1).getName()).isEqualTo("Beta");
            assertThat(result.get(2).getName()).isEqualTo("Gamma");
        }
    }

    // ─── getPopularTags ───────────────────────────────────────────────────────

    @Nested
    @DisplayName("getPopularTags")
    class GetPopularTagsTests {

        @Test
        @DisplayName("應該依 usageCount 回傳熱門標籤，並在多一筆時給出下一頁 cursor")
        void shouldReturnTagsOrderedByUsageCount() {
            Tag tag1 = createTagWithId("Popular", "popular", null, 0);
            tag1.setUsageCount(100);
            Tag tag2 = createTagWithId("LessPopular", "less-popular", null, 0);
            tag2.setUsageCount(50);
            Tag tag3 = createTagWithId("Rare", "rare", null, 0);
            tag3.setUsageCount(1);
            when(tagRepository.findPopularPage(null, null, org.springframework.data.domain.Limit.of(3)))
                    .thenReturn(List.of(tag1, tag2, tag3));

            CursorResponse<TagDto> result = tagService.getPopularTags(null, 2);

            assertThat(result.items()).extracting(TagDto::getName).containsExactly("Popular", "LessPopular");
            Cursor next = Cursor.decode(result.nextCursor());
            assertThat(next.longKey()).isEqualTo(50);
            assertThat(next.id()).isEqualTo(tag2.getId());
        }
    }
}
